template: |
  Dummy template value to make release-drafter happy.
  We don't need the releaser (for now) but even though it is disabled, the configuration file
  validation demands the template key to be present and to have a non empty value.
autolabeler:
  # Add labels based on the affected files. Note we don't cover unpublished packages.
  - label: 'App: storybook'
    files:
      - apps/storybook/**
  - label: 'Package: design-systems'
    files:
      - packages/design-systems/**
  - label: 'Package: minitailorctl'
    files:
      - packages/minitailorctl/**
  - label: 'Package: monitoring'
    files:
      - packages/monitoring/**
  - label: "Package: dev-config"
    files:
      - packages/dev-config/**
  - label: 'Package: utils'
    files:
      - packages/utils/**
  - label: 'Package: auth'
    files:
      - packages/auth/**
  # Add labels based on the PR title, which is usually identical to the first commit in the PR and
  # follows the Conventional Commit messages convention.
  - label: 'Type: Feature'
    title:
      - '/^feat/i'
  - label: 'Type: Refactor'
    title:
      - '/^refactor/i'
  - label: 'Type: Fix'
    title:
      - '/^fix/i'
  - label: 'Type: House Keeping'
    title:
      - '/^chore/i'
