import { mapJsonToProps } from "../utils/ark-props";
import accordion_types from "./accordion.types.json";
import avatar_types from "./avatar.types.json";
import carousel_types from "./carousel.types.json";
import checkbox_types from "./checkbox.types.json";
import date_picker_types from "./date-picker.types.json";
import dialog_types from "./dialog.types.json";
import hover_card_types from "./hover-card.types.json";
import menu_types from "./menu.types.json";
import number_input_types from "./number-input.types.json";
import pagination_types from "./pagination.types.json";
import pin_input_types from "./pin-input.types.json";
import popover_types from "./popover.types.json";
import radio_group_types from "./radio-group.types.json";
import range_slider_types from "./range-slider.types.json";
import segment_group_types from "./segment-group.types.json";
import select_types from "./select.types.json";
import slider_types from "./slider.types.json";
import switch_types from "./switch.types.json";
import tabs_types from "./tabs.types.json";
import tags_input_types from "./tags-input.types.json";
import toast_types from "./toast.types.json";
import tooltip_types from "./tooltip.types.json";

export const accordionTypes = mapJsonToProps(accordion_types);
export const avatarTypes = mapJsonToProps(avatar_types);
export const carouselTypes = mapJsonToProps(carousel_types);
export const checkboxTypes = mapJsonToProps(checkbox_types);
export const datePickerTypes = mapJsonToProps(date_picker_types);
export const dialogTypes = mapJsonToProps(dialog_types);
export const hoverCardTypes = mapJsonToProps(hover_card_types);
export const menuTypes = mapJsonToProps(menu_types);
export const numberInputTypes = mapJsonToProps(number_input_types);
export const paginationTypes = mapJsonToProps(pagination_types);
export const pinInputTypes = mapJsonToProps(pin_input_types);
export const popoverTypes = mapJsonToProps(popover_types);
export const radioGroupTypes = mapJsonToProps(radio_group_types);
export const rangeSliderTypes = mapJsonToProps(range_slider_types);
export const segmentGroupTypes = mapJsonToProps(segment_group_types);
export const selectTypes = mapJsonToProps(select_types);
export const sliderTypes = mapJsonToProps(slider_types);
export const switchTypes = mapJsonToProps(switch_types);
export const tabsTypes = mapJsonToProps(tabs_types);
export const tagsInputTypes = mapJsonToProps(tags_input_types);
export const toastTypes = mapJsonToProps(toast_types);
export const tooltipTypes = mapJsonToProps(tooltip_types);
