name: Install and build

inputs:
  scope:
    required: true
    description: target scope to pass to pnpm

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'

    # update corepack because pnpm delegates some commands to npm behind the scenes and
    # out of date versions of corepack fail with "Usage Error: This project is configured to use pnpm"
    - name: update npm and then update corepack
      shell: bash
      run: |-
        npm i -g npm
        npm i -g corepack@0.24.1

    - name: setup pnpm
      shell: bash
      run: corepack enable

    - run: pnpm install --filter "${{ inputs.scope }}"
      shell: bash

    - run: pnpm run build --filter "${{ inputs.scope }}"
      shell: bash
