name: Chromatic Deployment

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - apps/storybook/**
      - packages/design-systems/**
      - .github/workflows/chromatic.yml
      - .github/actions/ci/action.yml

jobs:
  publish-to-chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - uses: ./.github/actions/install_and_build
        with:
          scope: storybook

      - name: Prepare css for storybook
        run: pnpm run panda
        working-directory: ./apps/storybook

      - name: Publish storybook to chromatic
        id: chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/storybook
          exitZeroOnChanges: true

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: chromatic-url
          message: |
            Storybook preview URL (for ${{ github.sha }}): <${{ steps.chromatic.outputs.storybookUrl }}>
            <sub>Build URL: ${{ steps.chromatic.outputs.buildUrl }}</sub>
