name: Create release tag

on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  check-packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.output_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: output_matrix
        run: |
          echo "matrix=$(ls packages | jq -R -s -c '{ "package": split("\n")[:-1] }')" > $GITHUB_OUTPUT

  create-tag:
    runs-on: ubuntu-latest
    needs: check-packages
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.check-packages.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check version tag exists
        id: tag-exists
        working-directory: packages/${{ matrix.package }}
        continue-on-error: true
        run: |
          version="$(cat ./package.json | jq -r .version)"
          echo "version=$version" >> "$GITHUB_OUTPUT"

          git tag --list | grep "${{matrix.package}}/$(cat ./package.json | jq -r .version)" -c
      - name: Create tag
        if: steps.tag-exists.outcome == 'failure'
        run: |
          tag="${{matrix.package}}/${{ steps.tag-exists.outputs.version }}"
          git tag "$tag"
          git push origin "$tag"
