name: Create Github release

on: push

env:
  PACKAGE_NAME: utils
  NEXT_TAG: "0.4.0"

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the latest release
        uses: actions/github-script@v7
        with:
          script: |
            const { PACKAGE_NAME, NEXT_TAG } = process.env
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            const targetReleases = releases.filter(({ tag_name }) => tag_name.startsWith(PACKAGE_NAME))
            const { tag_name: previousReleaseTag } = targetReleases[0]
            console.log("Previous release:", previousReleaseTag)

            // Generatea a releaese note
            const generatedRelease = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `${PACKAGE_NAME}/${NEXT_TAG}`,
              previous_tag_name: previousReleaseTag,
            })

            console.log(generatedRelease.body)

