name: create github release

on:
  workflow_call:
    inputs:
      package_name:
        type: string
        required: true
        description: The name of the package.
      tag:
        type: string
        required: true
        description: The name of the tag to checkout.

permissions:
  contents: write

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}

      - name: Generate a release note
        uses: orhun/git-cliff-action@v3
        id: generate-release-note
        with:
          args: --include-path="packages/${{ inputs.package_name }}/*" --current --tag-pattern="${{ inputs.package_name }}"

      - name: Create a release note on Github
        uses: actions/github-script@v7
        with:
          script: |
            const { tag_name, body } = process.env
            await github.rest.repos.createRelease({
              ...context.repo,
              tag_name,
              body,
            })
        env:
          tag_name: ${{ inputs.tag }}
          body: ${{ steps.generate-release-note.outputs.changelog }}


