name: Create Github release

on: push

env:
  PACKAGE_NAME: utils
  NEXT_TAG: "0.4.0"

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate a release note between the previous release and the upcoming next
        uses: actions/github-script@v7
        with:
          script: |
            const { PACKAGE_NAME, NEXT_TAG } = process.env
            const { data: releases } = await github.rest.repos.listReleases({
              ...context.repo
            })
            const targetReleases = releases.filter(({ tag_name }) => tag_name.startsWith(PACKAGE_NAME))
            const { tag_name: previousReleaseTag } = targetReleases[0]
            console.log("Previous release:", previousReleaseTag)

            // Build a tag for next release
            const nextReleaseTag = `${PACKAGE_NAME}/${NEXT_TAG}`
            console.log("Next release:", nextReleaseTag)

            // Generatea a releaese note
            const { data: generatedReleaseNote } = await github.rest.repos.generateReleaseNotes({
              ...context.repo
              tag_name: `${PACKAGE_NAME}/${NEXT_TAG}`,
              previous_tag_name: previousReleaseTag,
            })

            return generatedRelaseNote

