name: Auto labeler

on: pull_request

permissions:
  contents: read

jobs:
  add_labels:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add labels
        uses: release-drafter/release-drafter@v6
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
