name: release package manually

on:
  workflow_call:
    inputs:
      package:
        type: string
        required: true
        description: The name of the package.
      version:
        type: string
        required: true
        description: The version of the package.

permissions:
  contents: write
  packages: write

jobs:
  github-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.target.outputs.current }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "${{ inputs.package }}/${{ inputs.version }}"
      - name: Check version matches package.json version
        working-directory: packages/${{ inputs.package }}
        run: |
          test "$(cat ./package.json | jq -r .version)" = ${{ inputs.version }}
      - name: Specify target
        id: target
        run: |
          current="${{ inputs.package }}/${{ inputs.version }}"
          prev="$(git tag --list | grep -B 1 "$current" | head -n 1)"
          echo "current=$current" >> "$GITHUB_OUTPUT"
          echo "prev=$prev" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Generate a release note
        uses: orhun/git-cliff-action@v3
        id: generate-release-note
        with:
          config: .github/cliff.toml
          args: --include-path="packages/${{ inputs.package }}/*" --tag-pattern="${{ inputs.package }}/*" ${{ steps.target.outputs.prev }}..${{ steps.target.outputs.current }}
      - name: GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ steps.generate-release-note.outputs.changelog }}
          tag_name: "${{ inputs.package }}/${{ inputs.version }}"
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-npm-package:
    needs: github-release
    uses: ./.github/workflows/publish_npm_package.yml
    secrets: inherit
    with:
      package_name: ${{ inputs.package }}
      tag: ${{ needs.github-release.outputs.tag }}

        