name: release package

on:
  push:
    branches: main
    tags: "*/*"

permissions:
  contents: write
  packages: write

jobs:
  extract-info:
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.extract.outputs.package }}
      version: ${{ steps.extract.outputs.version }}
    steps:
      - name: Extract package and version
        id: extract
        run: |
          package="$(echo ${{ github.ref_name }} | sed -E 's/([^\/]*)\/([^\/]*)/\1/')"
          version="$(echo ${{ github.ref_name }} | sed -E 's/([^\/]*)\/([^\/]*)/\2/')"
          echo "package=$package" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check version matches package.json version
        working-directory: packages/${{ steps.extract.outputs.package }}
        run: |
          test "$(cat ./package.json | jq -r .version)" = ${{ steps.extract.outputs.version }}
  
  github-release:
    runs-on: ubuntu-latest
    needs: extract-info
    steps:
      - name: Generate a release note
        uses: orhun/git-cliff-action@v3
        id: generate-release-note
        with:
          config: .github/cliff.toml
          args: --include-path="packages/${{ needs.extract-info.outputs.package }}/*" --tag-pattern="${{ needs.extract-info.outputs.package }}/* --current"
      - name: GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ steps.generate-release-note.outputs.changelog }}
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-npm-package:
    needs:
      - github-release
      - extract-info
    uses: ./.github/workflows/publish_npm_package.yml
    secrets: inherit
    with:
      package_name: ${{ needs.extract-info.outputs.package }}
      tag: ${{ github.ref }}
